version: '3.8'

services:
  docparser:
    build: .
    ports:
      - "7860:7860"
      - "6010:6010"
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=1
    shm_size: 16gb