version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: docparser-app:latest
    container_name: docparser-app
    restart: unless-stopped

    # vLLM (9998) ve FastAPI (7860) ikisini de dışarı aç
    ports:
      - "7860:7860"
      - "9998:9998"

    # Ağırlıkları host'tan bağla (klasör adı noktasız!)
    volumes:
      - weights/DotsOCR:/workspace/weights/DotsOCR:ro

    # GPU erişimi (Compose v2 çözümü)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # GPU seçimi için env (Compose 'deploy' yoksa env ile de seçebilirsin)
    environment:
      HF_MODEL_PATH: /workspace/weights/DotsOCR
      NVIDIA_VISIBLE_DEVICES: "1"
