version: "3.9"

services:
  ocr-app:
    build:
      context: .                # Dockerfile'ın bulunduğu dizin
      dockerfile: Dockerfile
    container_name: doc-parser-app
    ports:
      - "7860:7860"              # Gradio UI
      - "6010:6010"              # VLM server
    runtime: nvidia              # GPU erişimi
    deploy:
      restart_policy:
        condition: on-failure 
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=1
    