version: "3.8"

services:
  app:
    build:
      context: ..                # Build context PROJE KÖKÜ
      dockerfile: docker/Dockerfile
    image: docparser-app:latest
    container_name: docparser-app
    restart: unless-stopped

    # vLLM (9998) + FastAPI (7860)
    ports:
      - "7860:7860"
      - "9998:9998"

    # Ağırlıkları host'tan bağla (compose dosyası docker/ altında olduğu için ../ kullan)
    volumes:
      - ../weights/DotsOCR:/workspace/weights/DotsOCR:ro

    # GPU erişimi (Compose v2)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']     # host’taki 1 no’lu GPU'yu istiyorum
              capabilities: [gpu]

    environment:
      HF_MODEL_PATH: /workspace/weights/DotsOCR
