version: "3.8"

services:
  docparser-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    image: docparser-app:latest
    container_name: docparser-app
    restart: unless-stopped

    environment:
      APP_PORT: "7860"
      VLLM_HOST: "host.docker.internal"
      VLLM_PORT: "6013"

    # Linux'ta host.docker.internal -> host-gateway eşlemesi
    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "7860:7860"
