x-doc-parser-base: &doc-parser-base
  image: monkeyocr:latest
  volumes:
    - model_data:/app/MonkeyOCR/model_weight
  environment:
    - TMPDIR=/app/tmp
    - CUDA_VISIBLE_DEVICES=1
    - HF_HUB_CACHE=/app/MonkeyOCR/model_weight
    - MODELSCOPE_CACHE=/app/MonkeyOCR/model_weight
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  doc-parser:
    <<: *doc-parser-base
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "1"
        LMDEPLOY_PATCHED: "false"
    ports:
      - "7860:7860"

  doc-parser-fix:
    <<: *doc-parser-base
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "1"
        LMDEPLOY_PATCHED: "true"
    environment:
      - TMPDIR=/app/tmp
      - CUDA_VISIBLE_DEVICES=1
      - HF_HUB_CACHE=/app/MonkeyOCR/model_weight
      - MODELSCOPE_CACHE=/app/MonkeyOCR/model_weight
    ports:
      - "7860:7860"

  doc-parser-demo:
    <<: *doc-parser-base
    entrypoint: ["/app/MonkeyOCR/entrypoint.sh"]
    command: ["demo"]
    ports:
      - "7860:7860"

  doc-parser-dev:
    <<: *doc-parser-base
    entrypoint: ["/app/MonkeyOCR/entrypoint.sh"]
    command: ["bash"]
    stdin_open: true
    tty: true
    ports:
      - "7860:7860"

  doc-parser-api:
    <<: *doc-parser-base
    entrypoint: ["/app/MonkeyOCR/entrypoint.sh"]
    command: ["fastapi"]
    ports:
      - "7860:7860"
    environment:
      - TMPDIR=/app/tmp
      - CUDA_VISIBLE_DEVICES=1
      - HF_HUB_CACHE=/app/MonkeyOCR/model_weight
      - MODELSCOPE_CACHE=/app/MonkeyOCR/model_weight
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=7860

volumes:
  model_data: